language: python
python:
  - "3.5"
  - "3.6"

script:
  - pytest

deploy:
  provider: pypi
  user:
    secure: WqpF3kadgm1DhjFqK3BvjwB7//PT/YtZMgctoy2GXDLYmxM87tbyUVJJBrhEIoKKWKRdqjJyU5wG2Gyadvbg3d7PB1b2vIG81+ATuY9fSgGlQMMUwocsqK3pWpGEhQl5KVJV4Gvb5bl6pygnLS13UZv12Ak1fKwtAewUG7FEPIpk93OI5yxLRHlY4nrcS6WpXjjWJqWTY3jsN6LRDwgIZhuVBKS6lVmgUH+8mRTLgVbk4lrU51yymDKXOMln06VWzZkrQWFJJkI1EyHYXjaRFecKYhdQ+CBL/hbQt510xUyVgIJ8Zdez+q1EQqDxA5ED064yyQRkgAlELc8KJa1jWu0B5STZL42jhY20W64ezHMM/9EKrQr3tqTR5gKx2OtzVAXhCKYf+bNE4mLpacGrh1pkJnsfdhJCJgbu5AmM1blpMVGcN+xge9uIsPhwYqDWgZJ09BckE4HHX/tvWW9weYqLB049tp9BOcCC2g5HExP4VYDycq1L4XbkLoPB+oa1kkIbajRy0PYtHzNeGMKTppIWXQXEa6T6M+Aabloyf6PJu4HNo7W0ki8d8x1YUQYIMGqsICiDbFD/m4dBjbU3LTBzJyIwcDaOTdNruorWL6vUUH9cvQGqfeNF+NhBxNYqP6FFOmnCxQxTvtcNUuKFfkOh1l31/wxoLDWVHx8midY=
  password:
    secure: I4HSrjXzbUnQkAgTNyHm2oraTeeIFbng7YB8tpgScD01I/lXP9TCfyWH7sPWii5pDPraTVqhFdGMTKHhiAq3vIKo3g2Q7S9VuQUVn/Vgz8psXykxavng67zWIGKfUipHFMA7B+LdnV3hqUI7KN+ByPZMduEdvZa4Z+FRmWmCZQdGrEi1okULoiihcX5SZFKYgNIeeIRFevRyS84aYvlSfedSozh6SshAU7b8ZTav7pCXDfSK+JY6uom5Mo1HMK9Tgp9YnaqLk7Z2/91D1Qs9bnasb+fzapby65T7HtKAKGjyys8S0E7X0q8e4QuavN+ETKYae4yzxQzuI2T5xdpHC6r8mjrqymqMQtJ6/tkBjL+tYNqWzgT/em0+el/F9F89Cg3P5vseImmbQx4t5CqupBnyPmlUKnu1mah7pUBrq8ev8N8hR/nKQ5WlrHjhN7Rr9rNN7vLCxrF7pv7yMBjDexJDgIvW3TmTEaGrI7Yhau+ah2an/PJxYNFOtp9YBqqsdx2/2VGagHND0aF/nhhhKvwuc84RmX0w12V8Utr0gAksKmQz/JCT8DiZlIC6vU74IiuW94ex00XDai7wa0I4xzwaub2zxpaNXBysEQFN09BIjmKCRiFegooHgdp7UkLCF8OPfXVdwWl6yo8w9duip29ipBarOq57mFEKvdsRWZw=
  on:
    tags: true
